
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <title>Conjugation practice</title>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\">\n";
echo "    <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css\">\n";
echo "    <script src=\"http://code.jquery.com/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\n";
echo "    <script>\n";
echo "    </script>\n";
echo "</head>\n";
echo "<body>\n";
echo "<nav class=\"navbar navbar-default nav-fixed\">\n";
echo "    <div class=\"navbar-header\">\n";
echo "        <button data-target=\"#navbarCollapse\" data-toggle=\"collapse\" class=\"navbar-toggle\" type=\"button\">\n";
echo "            <span class=\"sr-only\">Toggle navigation</span>\n";
echo "            <span class=\"icon-bar\"></span>\n";
echo "            <span class=\"icon-bar\"></span>\n";
echo "            <span class=\"icon-bar\"></span>\n";
echo "        </button>\n";
echo "        <a id=\"a_main\" href=\"#\" class=\"navbar-brand\">Home</a>\n";
echo "    </div>\n";
echo "    <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\n";
echo "        <ul class=\"nav navbar-nav\">\n";
echo "            <li><a id=\"a_exec\" href=\"#\">Exercise</a></li>\n";
echo "            <li><a id=\"a_query\" href=\"#\">Query</a></li>\n";
echo "        </ul>\n";
echo "    </div>\n";
echo "</nav>\n";
echo "<div id=\"tab_main\" class=\"container\">\n";
echo "    <div class=\"jumbotron\">\n";
echo "        <h1>Conjugation practice</h1>\n";
echo "        <br />\n";
echo "        <p>Practice your verbs</p>\n";
echo "    </div>\n";
echo "</div>\n";
echo "</body>\n";
echo "</html>";
